import asyncio
import websockets
import httpx
import json
import pycrdt as Y

WS_URL = "ws://127.0.0.1:8000/ws/doc_test_ai"
HTTP_URL = "http://127.0.0.1:8000/documents/doc_test_ai/ai-edit"

async def test_ai_flow():
    # 1. Open WebSocket connection to represent the Human User
    async with websockets.connect(WS_URL) as ws:
        print("[Human Client] Connected to document socket.")
        
        # Receive initial sync bytes and initialize YDoc
        initial_message = await ws.recv()
        doc = Y.Doc()
        doc.apply_update(initial_message[1:])
        text = doc.get("text", type=Y.Text)
        
        # 2. Human client types a sentence
        print("[Human Client] Typing: 'The weather today is very cold.'")
        with doc.transaction():
            text += "The weather today is very cold."
        
        # Send update with Tag 0x00
        await ws.send(b"\x00" + doc.get_update())
        await asyncio.sleep(1) # wait for server database to sync
        
        # 3. Human client triggers the AI Editor via HTTP API POST request
        prompt = "Change the word cold to warm"
        print(f"[Human Client] Triggering AI Edit: '{prompt}'...")
        
        # Call the POST API
        async with httpx.AsyncClient() as http_client:
            response = await http_client.post(HTTP_URL, json={"prompt": prompt}, timeout=20.0)
            print(f"[Server Response] HTTP Status: {response.status_code}, Payload: {response.json()}")
            
        # 4. Wait to receive the Yjs sync broadcast generated by the AI
        print("[Human Client] Listening for AI broadcast updates on WebSocket...")
        ai_message = await ws.recv()
        tag = ai_message[0]
        payload = ai_message[1:]
        
        if tag == 0:
            doc.apply_update(payload)
            final_text = str(text)
            print(f"[Human Client] Final converged document: '{final_text}'")
            
            # Simple assertion: check if text has either LLM output ("warm") or Mock indicator
            assert "warm" in final_text.lower() or "ai edit" in final_text.lower()
            print("✅ Success: AI edit merged and converged on client screen!")
        else:
            print(f"❌ Error: Received unexpected packet tag {tag}")

if __name__ == "__main__":
    asyncio.run(test_ai_flow())
